apiVersion: v1
kind: Service
metadata:
  name: vault-nodejs
  labels:
    app: vault-nodejs
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vault-nodejs